export const AlbumData = [
  {
    id: 1,
    name: "France",
    imageName: "P1050369-min.jpg",
    comment: "Album photos France",
    byAlbums: [
      {
        id: 1,
        name: "Paris",
        imageName: "P1030503-min.jpg",
        comment: "Album photos Paris",
        images: [
          {
            id: 1,
            name: "France",
            imageName: "P1010785-min.jpg",
            comment: "pont lever du soleil",
          },
          {
            id: 2,
            name: "France",
            imageName: "P1010798-min.jpg",
            comment: "rue lever du soleil noir et blanc",
          },
          {
            id: 3,
            name: "France",
            imageName: "P1030483-min.jpg",
            comment: "clocher Montmartre coucher du soleil",
          },
          {
            id: 4,
            name: "France",
            imageName: "P1030488-min.jpg",
            comment: "Montmartre clocher avion",
          },
          {
            id: 5,
            name: "France",
            imageName: "P1030503-min.jpg",
            comment: "Montmartre coucher du soleil Paris",
          },
          {
            id: 6,
            name: "France",
            imageName: "P1030768-min.jpg",
            comment: "Bercy métro en mouvement",
          },
          {
            id: 7,
            name: "France",
            imageName: "P1030789-min.jpg",
            comment: "Pont Léopold Sédar Senghor",
          },
          {
            id: 8,
            name: "France",
            imageName: "P1040166-min.jpg",
            comment: "Architecture La Défense",
          },
          {
            id: 9,
            name: "France",
            imageName: "P1040177-min.jpg",
            comment: "La Défense circulation",
          },
          {
            id: 10,
            name: "France",
            imageName: "P1040223-2-min.jpg",
            comment: "Touristes à Paris",
          },
          {
            id: 11,
            name: "France",
            imageName: "P1040448-min.jpg",
            comment: "Manifestations réforme des retraites",
          },
          {
            id: 12,
            name: "France",
            imageName: "P1040615-min.jpg",
            comment: "Manifestations policier de dos",
          },
          {
            id: 13,
            name: "France",
            imageName: "P1040724-min.jpg",
            comment: "Sacré-cœur la nuit",
          },
          {
            id: 14,
            name: "France",
            imageName: "P1040765-min.jpg",
            comment: "Tour Eiffel lever du soleil",
          },
          {
            id: 15,
            name: "France",
            imageName: "P1040765-min.jpg",
            comment: "Tour Eiffel lever du soleil",
          },
          {
            id: 16,
            name: "France",
            imageName: "P1050369-min.jpg",
            comment: "École Militaire Paris statue",
          },
          {
            id: 17,
            name: "France",
            imageName: "P1050405-min.jpg",
            comment: "École Militaire Paris",
          },
          {
            id: 18,
            name: "France",
            imageName: "P1070133-min.jpg",
            comment: "Prairie nuages",
          },
          {
            id: 19,
            name: "France",
            imageName: "P1070253-min.jpg",
            comment: "Centre Pompidou Paris",
          },
          {
            id: 20,
            name: "France",
            imageName: "P1070390-min.jpg",
            comment: "Passerelle Léopold",
          },
          {
            id: 21,
            name: "France",
            imageName: "P1070465-Modifier-min.jpg",
            comment: "Fenêtres jaunes",
          },
          {
            id: 22,
            name: "France",
            imageName: "P1070635-Modifier-min.jpg",
            comment: "Pont de Bercy",
          },
          {
            id: 23,
            name: "France",
            imageName: "P1070724-Modifier-min.jpg",
            comment: "Chevalier Lune",
          },
          {
            id: 24,
            name: "France",
            imageName: "P1070836i-min.jpeg",
            comment: "Tonnerre sur la Tour Eiffel",
          },
        ],
      },
      {
        id: 2,
        name: "Gap",
        imageName: "P1070992-min.jpeg",
        comment: "Album photos Gap",
        images: [
          {
            id: 1,
            name: "France",
            imageName: "P1070921-min.jpeg",
            comment: "Départ en vacances sunrise",
          },
          {
            id: 2,
            name: "France",
            imageName: "P1070928-min.jpeg",
            comment: "Pose longue sunrise",
          },
          {
            id: 3,
            name: "France",
            imageName: "P1070979-min.jpeg",
            comment: "Montagne",
          },
          {
            id: 4,
            name: "France",
            imageName: "P1070980 2-min.jpeg",
            comment: "Les deux faces de la montagne",
          },
          {
            id: 5,
            name: "France",
            imageName: "P1070992-min.jpeg",
            comment: "Montagnes japonaises",
          },
          // {
          //   id: 6,
          //   name: "France",
          //   imageName: "P1070992-min.jpeg",
          //   comment: "Montagnes japonaises",
          // },
        ],
      },
    ],
  },
  {
    id: 2,
    name: "États-Unis",
    imageName: "P1060402-min.jpeg",
    comment: "Album photos États-Unis",
    byAlbums: [
      {
        id: 1,
        name: "Los Angeles",
        imageName: "P1060665-min.jpeg",
        comment: "Album photos Los Angeles",
        images: [
          {
            id: 1,
            name: "États-Unis",
            imageName: "P1060344-min.jpg",
            comment: "Vue de Los Angeles en Noir et Blanc",
          },
          {
            id: 2,
            name: "États-Unis",
            imageName: "P1060665-min.jpeg",
            comment: "États-Unis montgolfière",
          },
        ],
      },
      {
        id: 2,
        name: "San Francsico",
        imageName: "P1060912-min.jpeg",
        comment: "Album photos San Francsico",
        images: [
          {
            id: 1,
            name: "États-Unis",
            imageName: "P1060402-min.jpeg",
            comment: "Pacific Grove",
          },
          {
            id: 2,
            name: "États-Unis",
            imageName: "P1060491-Modifier-min.jpg",
            comment: "San Francisco",
          },
          {
            id: 3,
            name: "États-Unis",
            imageName: "P1060879-min.jpeg",
            comment: "San Francisco sunset",
          },
          {
            id: 4,
            name: "États-Unis",
            imageName: "P1060912-min.jpeg",
            comment: "Golden Gate Bridge sunset",
          },
        ],
      },
    ],
  },
  {
    id: 3,
    name: "Italie",
    imageName: "P1030422-min.jpg",
    comment: "Album photos Italie",
    byAlbums: [
      {
        id: 1,
        name: "Rome",
        imageName: "P1030413-min.jpg",
        comment: "Album photos Rome",
        images: [
          {
            id: 1,
            name: "Italie",
            imageName: "P1030311-min.jpg",
            comment: "Italie automne",
          },
          {
            id: 2,
            name: "Italie",
            imageName: "P1030413-min.jpg",
            comment: "L’Arc de Titus Rome",
          },
          {
            id: 3,
            name: "Italie",
            imageName: "P1030422-min.jpg",
            comment: "Le Colisée Rome",
          },
          {
            id: 4,
            name: "Italie",
            imageName: "P1060040-min.jpeg",
            comment: "Une rue romaine",
          },
        ],
      },
    ],
  },
];
